task: 'deform'
gpus: [0]

parent_cfg: 'configs/aligned_nerf_pdf/aligned_aninerf_pdf_s9p.yaml'

train_dataset:
    data_root: 'data/mixamo_human/malcolm'
    human: 'rp_malcolm'
    ann_file: 'data/mixamo_human/malcolm/annots.npy'
    split: 'train'

test_dataset:
    data_root: 'data/mixamo_human/malcolm'
    human: 'rp_malcolm'
    ann_file: 'data/mixamo_human/malcolm/annots.npy'
    split: 'test'

test:
    frame_sampler_interval: 10

erode_edge: False


# data options
# H: 1002
# W: 1000
ratio: 1.
training_view: [1, 4, 7, 9]
init_aninerf: 'no_pretrain'
num_train_frame: 70
num_eval_frame: 70
begin_ith_frame: 0
frame_interval: 1
smpl: 'smpl'
vertices: 'vertices'
params: 'params'
use_bigpose: True
big_box: True
box_padding: 0.1
