task: 'deform'
gpus: [0]

parent_cfg: 'configs/sdf_pdf/anisdf_pdf_s9p.yaml'

train_dataset:
    data_root: 'data/loose_cloth/CHH/bodydata'
    human: 'chh'
    ann_file: 'data/loose_cloth/CHH/bodydata/annots.npy'
    split: 'train'

test_dataset:
    data_root: 'data/loose_cloth/CHH/bodydata'
    human: 'chh'
    ann_file: 'data/loose_cloth/CHH/bodydata/annots.npy'
    split: 'test'


# data options
# H: 1002
# W: 1000
ratio: 1.
training_view: [0]
test_view: [0]
num_latent_code: 72
num_train_frame: 72
num_eval_frame: 60
begin_ith_frame: 0
frame_interval: 5
smpl: 'smpl'
vertices: 'vertices'
params: 'params'
big_box: True
box_padding: 0.1
