task: 'deform'
gpus: [0]

parent_cfg: 'configs/aligned_nerf_lbw/aligned_aninerf_lbw_s9p.yaml'

train_dataset:
    data_root: 'data/deepcap/vlad_images1011'
    human: 'Vlad'
    ann_file: 'data/deepcap/vlad_images1011/annots.npy'
    split: 'train'

test_dataset:
    data_root: 'data/deepcap/vlad_images1011'
    human: 'Vlad'
    ann_file: 'data/deepcap/vlad_images1011/annots.npy'
    split: 'test'

test:
    frame_sampler_interval: 30

# data options
# H: 1002
# W: 1000
ratio: 1.
training_view: [66]
test_view: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
init_aninerf: 'no_pretrain'
num_train_frame: 300
num_eval_frame: 300
begin_ith_frame: 0
frame_interval: 1
smpl: 'smpl'
vertices: 'vertices'
params: 'params'
use_bigpose: True
big_box: True
box_padding: 0.05
