task: 'deform'
gpus: [0]

parent_cfg: 'configs/aligned_nerf_lbw/aligned_aninerf_lbw_s9p.yaml'

train_dataset:
    data_root: 'data/light_stage/CoreView_386'
    human: 'CoreView_386'
    ann_file: 'data/light_stage/CoreView_386/annots.npy'
    split: 'train'

test_dataset:
    data_root: 'data/light_stage/CoreView_386'
    human: 'CoreView_386'
    ann_file: 'data/light_stage/CoreView_386/annots.npy'
    split: 'test'

test:
    frame_sampler_interval: 30

# data options
# H: 1002
# W: 1000
ratio: 0.5
training_view: [0, 6, 12, 18]
init_aninerf: 'no_pretrain'
num_train_frame: 300
num_eval_frame: 1000
begin_ith_frame: 0
frame_interval: 1
smpl: 'new_smpl'
vertices: 'new_vertices'
params: 'new_params'
use_bigpose: True
big_box: True
box_padding: 0.05
